# alias mios que deben agregarse en el home
# recordar que es .bash_aliases
alias ll='ls -alh'
alias t2='tree -L 2 -sh'
alias suspend='systemctl suspend'

# vim
alias v='vim'

# transparency
alias transparency='/home/leandro/Documents/GNULinux/scripts/transparency.sh'

# markdown
alias md='/home/leandro/Documents/GNULinux/scripts/md.sh'

# wttr
alias wttr='/home/leandro/Documents/GNULinux/scripts/wttr.sh'
alias wttr2='/home/leandro/Documents/GNULinux/scripts/wttr2.sh'

# rclone
alias baulera='/home/leandro/Documents/GNULinux/scripts/baulera.sh'
alias edm='/home/leandro/Documents/GNULinux/scripts/edm.sh'
alias fiat147='/home/leandro/Documents/GNULinux/scripts/fiat147.sh'
alias gnulinux='/home/leandro/Documents/GNULinux/scripts/gnulinux.sh'
alias gugler='/home/leandro/Documents/GNULinux/scripts/gugler.sh'
alias rata='/home/leandro/Documents/GNULinux/scripts/rata.sh'
alias tuped='/home/leandro/Documents/GNULinux/scripts/tuped.sh'
alias sadio='/home/leandro/Documents/GNULinux/scripts/sadio.sh'

# rsync Linode
#alias linode='/home/leandro/Documents/Gugler/PHP/syncLinode.sh'
alias linode='/home/leandro/Documents/GNULinux/scripts/linode.sh'

# rsync Raspberry Pi Zero
alias rpiz='/home/leandro/Documents/Gugler/PHP/syncRpiz.sh'

# systemd
alias scs='systemctl status'

# mikrotik
alias mikrotik='/home/leandro/Documents/GNULinux/scripts/mikrotik.sh'

# git
alias git_graph='git log --all --decorate --oneline --graph'

# countdown
alias countdown='/home/leandro/Documents/GNULinux/scripts/Examples/countDown.sh'

