! ------------------------------------------------------------------------------
! ROFI Color theme
! User: leandro
! ------------------------------------------------------------------------------
rofi.separator-style: solid
!
rofi.color-window: argb:ee272822, #323234, #f30206
rofi.color-normal: argb:00272822, #d4d4d6, argb:00272822, #f30206, #ffffff
rofi.color-active: argb:00272822, #f30206, argb:00272822, #f30206, #eeeeee
rofi.color-urgent: argb:00272822, #dc322f, argb:00272822, #dc322f, #fdf6e3
