#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --distribution buster \
    --architectures amd64 \
    --debian-installer false \
    --archive-areas "main contrib non-free" \
    --apt aptitude \
    --apt-indices false \
    --memtest none \
    --bootappend-live "boot=live components keyboard-layouts=us keyboard-variants=dvorak \
                       persistence persistence-encryption=luks"
    "${@}"
